Repository RedDot15/FS_LiveTalking, pull requests merged in 2025-08, with the labels that each got.

#1 add xtts voice clone
  .gitignore
  app.py
  basereal.py
  female.wav
  lipreal.py
  llm.py
  llm_response.ipynb
  morty.wav
  thang.wav
  thangngot.wav
  ttsreal.py
Labels: Feature

#9 livetalking-dockercompose
  .env.dev
  .gitignore
  docker-compose.yml
  dockers/Dockerfile
  dockers/Dockerfile.livetalking
  libs/realistic/src/realistic/wav2lip/settings.py
  libs/text_to_speech/src/text_to_speech/xtts.py
  libs/text_to_speech/src/text_to_speech/xtts/settings.py
  libs/text_to_speech/src/text_to_speech/xtts/xtts.py
  services/livetalking/src/livetalking/settings.yaml
  services/livetalking/src/livetalking/shared/settings/settings.py
  uv.lock
Labels: Refactor

#10 full pipeline livetalking service
  docker-compose.yml
  dockers/Dockerfile.frontend
  services/livetalking/src/livetalking/__init__.py
  web/client.js
  web/dashboard.html
  web/webrtcapi.html
Labels: Feature, Refactor

#11 Minio Lib
  docker-compose.yml
  libs/minio_client/README.md
  libs/minio_client/pyproject.toml
  libs/minio_client/src/minio_client/__init__.py
  libs/minio_client/src/minio_client/minio.py
  libs/minio_client/src/minio_client/py.typed
  libs/minio_client/src/minio_client/settings.py
  libs/minio_client/src/test/test.py
  libs/minio_client/src/test/test_minio.py
  libs/minio_client/src/test/testfile.txt
  pyproject.toml
  uv.lock
Labels: Feature
